apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: elysian-ingress
  labels:
    app.kubernetes.io/name: nginx-ingress
    app.kubernetes.io/version: "0.1"
    app.kubernetes.io/part-of: ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.org/mergeable-ingress-type: "master"
spec:
  rules:
    - host: k8s.debray.dev
